# [omo]tcha: modified the code auto-generated by casf
rm(list=ls());
require(boot);
method <- "rtm";

# [omo]tcha: set header to TRUE cannot read the first line
data_all <- read.table(paste(getwd(), "utils", "casf", method, "spearman_results", sep = "/"), header=FALSE);
data <- as.matrix(data_all[,2]);

mymean <- function(x,indices) sum(x[indices])/57;
data.boot <- boot(data,mymean,R=10000,stype="i",sim="ordinary");
sink(paste(getwd(), "utils", "casf", method, "spearman-ci.results", sep = "/"));
a <- boot.ci(data.boot,conf=0.9,type= "bca");
print(a);
sink();