# [omo]tcha: modified the code auto-generated by casf
rm(list=ls());
require(boot);
method <- "rtm";

# [omo]tcha: set header to TRUE cannot read the first line
data_all <- read.table(paste(getwd(), "utils", "casf", method, "processed_score", sep = "/"), header=FALSE);
aa <- seq_len(nrow(data_all));
mycore <- function(x,indices)
{
    data_1 <- matrix(NA,285,2);
    # [omo]tcha: fix grammar error
    for(i in 1:285)
    {
        data_1[i,1] <- data_all[x[indices][i], 2];
        data_1[i,2] <- data_all[x[indices][i], 3];
    };

    data_2 <- data.frame(data_1);
    names(data_2) <- c("a","b");
    cor(data_2$a,data_2$b);
}

data.boot <- boot(aa,mycore,R=10000,stype="i",sim="ordinary");
sink(paste(getwd(), "utils", "casf", method, "pearson-ci.results", sep = "/"));
a <- boot.ci(data.boot,conf=0.9,type= "bca");
print(a);
sink();